### ISSUE TITLE
[Google Forms Request]: Serasa

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#10]
### Bypass requested from Google Forms
Response ID: 17
### App to request
 Serasa
### App Store link
https://apps.apple.com/br/app/serasaconsumidor/id1102452668
### App version
8.18.0
### Jailbreak and iOS version
OdysseyRa1n, IOS 14.3
### Bypass tried
- A-Bypass
- Liberty Lite
- Hestia
- Shadow
- HideJB
- KernBypass
- vnodebypass
- Disabling tweak injection with Choicy or libhooker-configurator
### Which worked
n / a
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
App isn't available in my region and i can't change regions to test myself.

but i'll add it to the list anyway
