### ISSUE TITLE
[Google Forms Request]: Ame Digital

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#11]
### Bypass requested from Google Forms
Response ID: 18
### App to request
 Ame Digital
### App Store link
https://apps.apple.com/app/apple-store/id1371680463
### App version
1.53.6
### Jailbreak and iOS version
OdysseyRa1n, IOS 14.3
### Bypass tried
- A-Bypass
- Liberty Lite
- Hestia
- Shadow
- HideJB
- KernBypass
- vnodebypass
- Disabling tweak injection with Choicy or libhooker-configurator
### Which worked
n/a
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
![image](https://user-images.githubusercontent.com/29195927/148626873-e4250fce-d7a2-42e7-99eb-15c2d6a6e696.jpeg)
seems like the app is using iossecuritysuite...

**Comment by goodboydheeraj** [comment]
> ![image](https://user-images.githubusercontent.com/29195927/148626873-e4250fce-d7a2-42e7-99eb-15c2d6a6e696.jpeg)
> seems like the app is using iossecuritysuite...

What does it mean? Can’t ever bypass it?

**Comment by joshuah345** [comment]
~~it's using a swift library for jailbreak detection that i have a feeling many tweaks won't be able to bypass, at least for now~~

**Comment by joshuah345** [comment]
That was inaccurate, a-bypass works for this app
