### ISSUE TITLE
[Request]: Ziggo GO

### ISSUE THREAD

**Issue by adfsamski** [hekatos/manifests#12]
### App to request

Ziggo GO

### App Store link

https://apps.apple.com/nl/app/ziggo-go/id1156417365

### App version

4.34.4

### Jailbreak

Checkra1n

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [ ] Hestia
- [ ] Shadow
- [X] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

HideJB

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
added with shadow instead of hidejb (hidejb is a fork with no big changes)
