### ISSUE TITLE
[Request]: Add new Pokeworks app (old one, which is now retired, didn't need bypass)

### ISSUE THREAD

**Issue by kumashi73** [hekatos/manifests#17]
### App to request

Pokeworks

### App Store link

https://apps.apple.com/us/app/pokeworks/id1591233747

### App version

1.0

### Jailbreak

Taurine

### Bypass tried

- [X] A-Bypass
- [ ] Liberty Lite (Beta)
- [ ] Hestia
- [X] Shadow
- [ ] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

vnodebypass, Shadow

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
A-Bypass is working for me on unc0ver. noted
