### ISSUE TITLE
[Request]: Line

### ISSUE THREAD

**Issue by berlaychen** [hekatos/manifests#18]
### App to request

Line

### App Store link

https://apps.apple.com/tw/app/line/id443904275

### App version

11.15.0

### Jailbreak

Taurine

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [X] Shadow
- [X] HideJB
- [X] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
I don't think line has detection. You may want to try disabling tweaks for it Choicy/libhooker-configurator.

**Comment by berlaychen** [comment]
> I don't think line has detection. You may want to try disabling tweaks for it Choicy/libhooker-configurator.

In Taiwan, Line integrates Line Pay within Line app. When using Line Pay, it'll tell not supported in jailbroken.
Seems it uses DTTJailbreakDetection, but DTT can be bypassed with liberty lite, and mine doesn't work. Maybe they uses not only DTT but also with other detection method.
![image](https://user-images.githubusercontent.com/51433626/153440249-043be28a-b4e9-4b4d-b780-f977b20ba324.png)

**Comment by joshuah345** [comment]
Try the bypasses again with libhooker beta

https://repo.theodyssey.dev/libhooker-beta

**Comment by berlaychen** [comment]
> Try the bypasses again with libhooker beta
> 
> 
> 
> https://repo.theodyssey.dev/libhooker-beta

Still no luck 😔
