### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by Mint137** [hekatos/manifests#20]
### App to request

ADT Pulse

### App Store link

https://apps.apple.com/us/app/adt-pulse/id355736423

### App version

10.0.1

### Jailbreak

Odysseyrain 14.8

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [X] Shadow
- [ ] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

A-Bypass is the only one that doesn't cause it to crash on startup.

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Using the recommended instructions from https://hekatos.github.io, Shadow is working
will add soon
