### ISSUE TITLE
[Google Forms Request]: Kotak - 811 & Mobile Banking

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#21]
### Bypass requested from Google Forms
Response ID: 20
### App to request
 Kotak - 811 & Mobile Banking
### App Store link
https://apps.apple.com/in/app/kotak-811-mobile-banking/id622363400
### App version
5.2.3
### Jailbreak and iOS version
unc0ver + fugu 14 on ios 14.5
### Bypass tried
- A-Bypass
- Liberty Lite
- Disabling tweak injection with Choicy or libhooker-configurator
### Which worked
n/a
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
A-Bypass is working for this app
Liberty is broken on unc0ver rn

**Comment by joshuah345** [comment]
added in c7d64bfc2b177c8f639099cbac266e1061f953d8
meant to say #21, whoops
