### ISSUE TITLE
[Request]: Freestyle Libre 2

### ISSUE THREAD

**Issue by chris98898** [hekatos/manifests#22]
### App to request

FreeStyle Libre 2 - CA

### App Store link

https://apps.apple.com/ca/app/freestyle-libre-2-ca/id1472261764

### App version

No Listed Version

### Jailbreak

Taurine

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [ ] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] iHide
- [X] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Nothing — not even combinations have worked.

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by chris98898** [comment]
I think I should also mention that this app is very necessary for my health and I can’t enjoy a Jailbreak any longer until this app gets bypassed.

**Comment by joshuah345** [comment]
FreeStyle Libre and derivatives by abbott have kernel level jailbreak detection. unfortunately, there's nothing we can do about it at the moment

**Comment by chris98898** [comment]
Is there anyone I can speak to which I might be able to persuade otherwise? Jailbreaking poses no security risks for the Libre 2 application or the sensor.

**Comment by joshuah345** [comment]
Notable names are ryley angus (liberty developer), level3tjg and julioverne
