### ISSUE TITLE
[Google Forms Request]: Al-Bank

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#24]
### Bypass requested from Google Forms
Response ID: 22
### App to request
 Al-Bank
### App Store link
https://apps.apple.com/us/app/al-bank/id421357586
### App version
7.7.0
### Jailbreak and iOS version
Unc0ver 14.3
### Bypass tried
- A-Bypass
- Liberty Lite
- Hestia
- Shadow
- HideJB
- KernBypass
- vnodebypass
- Disabling tweak injection with Choicy or libhooker-configurator
### Which worked
No one did work
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
AL-Bank is already on the list. Closing this issue

**Comment by beer-psi** [comment]
> AL-Bank is already on the list. Closing this issue

Maybe a new update broke the working bypass?

**Comment by joshuah345** [comment]
> > AL-Bank is already on the list. Closing this issue
> 
> Maybe a new update broke the working bypass?

AL-Bank was listed for quite a while with no known bypass

**Comment by beer-psi** [comment]
> > > AL-Bank is already on the list. Closing this issue
> > 
> > 
> > Maybe a new update broke the working bypass?
> 
> AL-Bank was listed for quite a while with no known bypass

Oh :skull:
