### ISSUE TITLE
Umobile Alert Bypass

### ISSUE THREAD

**Issue by dinouse** [hekatos/manifests#26]
### App to request

Umobile

### App Store link

https://apps.apple.com/my/app/myumobile/id986248783

### App version

3.10.12

### Jailbreak

Checkra1n 

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [ ] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Auto Alert. I just dismiss the alert popup and it work.

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Going to add hestia as it has an alert dismiss function
