### ISSUE TITLE
[Request]: Tata Play Binge

### ISSUE THREAD

**Issue by goodboydheeraj** [hekatos/manifests#27]
### App to request

Tata Play Binge

### App Store link

https://apps.apple.com/in/app/tata-play-binge/id1555688122

### App version

3.0.3

### Jailbreak

Checkra1n

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [ ] Hestia
- [X] Shadow
- [ ] HideJB
- [ ] iHide
- [X] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [x] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

No bypasses are working so far
Decrypted .ipa link https://drive.google.com/u/0/uc?id=1WGvBIOX1aadNG73GYewt9jZ38RGs2cOs&export=download

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
no dice on my end
