### ISSUE TITLE
[Request]: SBI Card

### ISSUE THREAD

**Issue by goodboydheeraj** [hekatos/manifests#29]
### App to request

SBI Card

### App Store link

https://apps.apple.com/us/app/sbi-card/id694549848

### App version

7.3.15

### Jailbreak

Odysseyr1n

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [ ] Hestia
- [X] Shadow
- [x] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

None of the bypass works as of the app’s latest version 7.3.14. Vnodebypass works if the app is downgraded back to v7.3.13 or below.

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by goodboydheeraj** [comment]
Bypassed by which tweak? No bypass works for versions .14 & .15. Older version .13 works with Vnodebypass but is no longer supported by the bank

**Comment by joshuah345** [comment]
That was just to mark it as bypassed on lower versions
i'll add a different label instead
