### ISSUE TITLE
[Request]: InstaPay Egypt

### ISSUE THREAD

**Issue by MMFawal** [hekatos/manifests#32]
### App to request

InstaPay Egypt

### App Store link

https://apps.apple.com/eg/app/instapay-egypt/id1592108795

### App version

1.2.0

### Jailbreak

Unc0ver

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [X] Shadow
- [ ] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by Bewenben** [comment]
can we reopen this?, this app is really needed to have a bypass
