### ISSUE TITLE
[Google Forms Request]: Gojek

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#36]
### Bypass requested from Google Forms
Response ID: 24
### App to request
 Gojek
### App Store link
https://apps.apple.com/us/app/gojek/id944875099
### App version
4.43
### Jailbreak and iOS version
Odyssey, iOS 13.5
### Bypass tried
- A-Bypass
- Hestia
### Which worked
n/a
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
we have a tweak for this called GojekEnabler...
