### ISSUE TITLE
[Google Forms Request]: Sberbank

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#4]
### Bypass requested from Google Forms
Response ID: 13
### App to request
 Sberbank
### App Store link
https://apps.apple.com/ru/app/%D1%81%D0%B1%D0%B5%D1%80%D0%B1%D0%B0%D0%BD%D0%BA-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D1%81-%D1%81%D0%B0%D0%BB%D1%8E%D1%82%D0%BE%D0%BC/id492224193
### App version
 12.11.0
### Jailbreak and iOS version
Unc0ver 8.0.2 iOS 14.8
### Bypass tried
- A-Bypass
- Hestia
- Shadow
- HideJB
- vnodebypass
### Which worked
n/a
### Checklist submission
- The app is missing from the table, or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by Logonoff410** [comment]
Yes, this is a banking application, and it starts swearing only after logging into the account. We are very much waiting (there are many of us) Your help! Thanks!

**Comment by Logonoff410** [comment]
Maybe I can help you somehow? We realy need to bypass this app🙏
