### ISSUE TITLE
[Request]: SC Mobile Pakistan

### ISSUE THREAD

**Issue by abdulmunimajaz** [hekatos/manifests#42]
### App to request

SC Pakistan

### App Store link

https://apps.apple.com/pk/app/sc-mobile-pakistan/id645859445

### App version

3.0.0

### Jailbreak

unc0ver 8.0.2

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [X] Shadow
- [X] HideJB
- [X] iHide
- [X] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
will test soon and add to list
