### ISSUE TITLE
[Request]: MeeToo

### ISSUE THREAD

**Issue by Peachpops** [hekatos/manifests#43]
### App to request

MeeToo

### App Store link

https://apps.apple.com/gb/app/meetoo/id1192707038

### App version

1.9.1

### Jailbreak

unc0ver + Fugu14

### Bypass tried

- [ ] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Hestia

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Shadow is also working, will add soon
