### ISSUE TITLE
[Request]: TfL Go

### ISSUE THREAD

**Issue by Peachpops** [hekatos/manifests#44]
### App to request

TfL Go

### App Store link

https://apps.apple.com/gb/app/tfl-go-live-tube-bus-rail/id1419541638

### App version

1.26.5

### Jailbreak

unc0ver + Fugu14

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [X] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Hestia

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
A-Bypass and shadow are also working
noting that image check patches in Hestia has to be disabled for the app to not crash
