### ISSUE TITLE
[Request] Missing NBC Sports App

### ISSUE THREAD

**Issue by Goldstriker208** [hekatos/manifests#45]
### App to request

NBC Sports

### App Store link

https://apps.apple.com/us/app/nbc-sports/id542511686

### App version

8.7

### Jailbreak

Unc0ver

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [X] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] iHide
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
I just tested the app and i'm able to play videos etc just fine
Odysseyra1n on iOS 14.6
