### ISSUE TITLE
[Google Forms Request]: Livin' by Mandiri

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#46]
### Bypass requested from Google Forms
Response ID: 25
### App to request
 Livin' by Mandiri
### App Store link
https://apps.apple.com/id/app/livin-by-mandiri/id1555414743
### App version
1.1.1
### Jailbreak and iOS version
unc0ver 5.3.1 and ios 13.3
### Bypass tried
- Liberty Lite
- Shadow
- HideJB
### Which worked
Changes CFbundleShortVersionString value at info.plist files (ios 14.0 and above) using Filza (Var/mobile/container/data/application/Livin` by mandiri) seems to be worked. But since Iam on ios 13.3, I cannot find such a files. 
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
vnodebypass, a-bypass, shadow do not work
liberty is broken
