### ISSUE TITLE
[Google Forms Request]: FaceApp

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#5]
### Bypass requested from Google Forms
Response ID: 12
### App to request
 FaceApp
### App Store link
https://apps.apple.com/us/app/faceapp-face-editor/id1180884341
### App version
10.0.0
### Jailbreak and iOS version
unc0ver, iOS 14.8
### Bypass tried
- A-Bypass
- KernBypass
- vnodebypass
- Disabling tweak injection with Choicy or libhooker-configurator
### Which worked
A-Bypass
### Checklist submission
- The app is missing from the table, or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Works fine after enabling only A-Bypass with Choicy.

**Comment by joshuah345** [comment]
Added in 70cb66d351fd77bf95699df4334de49b20c0807c
