### ISSUE TITLE
[Request]: Sahel

### ISSUE THREAD

**Issue by amrfoudaas** [hekatos/manifests#7]
### App to request

Sahel

### App Store link

https://apps.apple.com/us/app/sahel-%D8%B3%D9%87%D9%84/id1581727068

### App version

1.3.0

### Jailbreak

Unc0ver

### Bypass tried

I have tried all available tweaks 

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by joshuah345** [comment]
Latest version of the app seems to remove jb detection... gotta edit it again
